from enum import Enum


class ADDRESS_STATE(Enum):
    AS_INSERVICE = 0
    AS_OUTOFSERVICE = 1


class CALLHUB_STATE(Enum):
    CHS_ACTIVE = 0
    CHS_IDLE = 1


class DISCONNECT_CODE(Enum):
    DC_NORMAL = 0
    DC_NOANSWER = 1
    DC_REJECTED = 2


class QOS_SERVICE_LEVEL(Enum):
    QSL_NEEDED = 1
    QSL_IF_AVAILABLE = 2
    QSL_BEST_EFFORT = 3


class FINISH_MODE(Enum):
    FM_ASTRANSFER = 0
    FM_ASCONFERENCE = 1


class CALL_STATE(Enum):
    CS_IDLE = 0
    CS_INPROGRESS = 1
    CS_CONNECTED = 2
    CS_DISCONNECTED = 3
    CS_OFFERING = 4
    CS_HOLD = 5
    CS_QUEUED = 6
    CS_LASTITEM = 7


class CALL_PRIVILEGE(Enum):
    CP_OWNER = 0
    CP_MONITOR = 1


class CALLINFO_LONG(Enum):
    CIL_MEDIATYPESAVAILABLE = 0
    CIL_BEARERMODE = 1
    CIL_CALLERIDADDRESSTYPE = 2
    CIL_CALLEDIDADDRESSTYPE = 3
    CIL_CONNECTEDIDADDRESSTYPE = 4
    CIL_REDIRECTIONIDADDRESSTYPE = 5
    CIL_REDIRECTINGIDADDRESSTYPE = 6
    CIL_ORIGIN = 7
    CIL_REASON = 8
    CIL_APPSPECIFIC = 9
    CIL_CALLPARAMSFLAGS = 10
    CIL_CALLTREATMENT = 11
    CIL_MINRATE = 12
    CIL_MAXRATE = 13
    CIL_COUNTRYCODE = 14
    CIL_CALLID = 15
    CIL_RELATEDCALLID = 16
    CIL_COMPLETIONID = 17
    CIL_NUMBEROFOWNERS = 18
    CIL_NUMBEROFMONITORS = 19
    CIL_TRUNK = 20
    CIL_RATE = 21
    CIL_GENERATEDIGITDURATION = 22
    CIL_MONITORDIGITMODES = 23
    CIL_MONITORMEDIAMODES = 24


class CALLINFO_STRING(Enum):
    CIS_CALLERIDNAME = 0
    CIS_CALLERIDNUMBER = 1
    CIS_CALLEDIDNAME = 2
    CIS_CALLEDIDNUMBER = 3
    CIS_CONNECTEDIDNAME = 4
    CIS_CONNECTEDIDNUMBER = 5
    CIS_REDIRECTIONIDNAME = 6
    CIS_REDIRECTIONIDNUMBER = 7
    CIS_REDIRECTINGIDNAME = 8
    CIS_REDIRECTINGIDNUMBER = 9
    CIS_CALLEDPARTYFRIENDLYNAME = 10
    CIS_COMMENT = 11
    CIS_DISPLAYABLEADDRESS = 12
    CIS_CALLINGPARTYID = 13


class CALLINFO_BUFFER(Enum):
    CIB_USERUSERINFO = 0
    CIB_DEVSPECIFICBUFFER = 1
    CIB_CALLDATABUFFER = 2
    CIB_CHARGINGINFOBUFFER = 3
    CIB_HIGHLEVELCOMPATIBILITYBUFFER = 4
    CIB_LOWLEVELCOMPATIBILITYBUFFER = 5


class CALL_STATE_EVENT_CAUSE(Enum):
    CEC_NONE = 0
    CEC_DISCONNECT_NORMAL = 1
    CEC_DISCONNECT_BUSY = 2
    CEC_DISCONNECT_BADADDRESS = 3
    CEC_DISCONNECT_NOANSWER = 4
    CEC_DISCONNECT_CANCELLED = 5
    CEC_DISCONNECT_REJECTED = 6
    CEC_DISCONNECT_FAILED = 7
    CEC_DISCONNECT_BLOCKED = 8


class CALL_NOTIFICATION_EVENT(Enum):
    CNE_OWNER = 0
    CNE_MONITOR = 1
    CNE_LASTITEM = 1


class TAPI_EVENT(Enum):
    TE_TAPIOBJECT = 1
    TE_ADDRESS = 2
    TE_CALLNOTIFICATION = 4
    TE_CALLSTATE = 8
    TE_CALLMEDIA = 16
    TE_CALLHUB = 32
    TE_CALLINFOCHANGE = 64
    TE_PRIVATE = 128
    TE_REQUEST = 256
    TE_AGENT = 512
    TE_AGENTSESSION = 1024
    TE_QOSEVENT = 2048
    TE_AGENTHANDLER = 4096
    TE_ACDGROUP = 8192
    TE_QUEUE = 16384
    TE_DIGITEVENT = 32768
    TE_GENERATEEVENT = 65536
    TE_ASRTERMINAL = 131072
    TE_TTSTERMINAL = 262144
    TE_FILETERMINAL = 524288
    TE_TONETERMINAL = 1048576
    TE_PHONEEVENT = 2097152
    TE_TONEEVENT = 4194304
    TE_GATHERDIGITS = 8388608
    TE_ADDRESSDEVSPECIFIC = 16777216
    TE_PHONEDEVSPECIFIC = 33554432


class CALLHUB_EVENT(Enum):
    CHE_CALLJOIN = 0
    CHE_CALLLEAVE = 1
    CHE_CALLHUBNEW = 2
    CHE_CALLHUBIDLE = 3
    CHE_LASTITEM = 3


class ADDRESS_CAPABILITY(Enum):
    AC_ADDRESSTYPES = 0
    AC_BEARERMODES = 1
    AC_MAXACTIVECALLS = 2
    AC_MAXONHOLDCALLS = 3
    AC_MAXONHOLDPENDINGCALLS = 4
    AC_MAXNUMCONFERENCE = 5
    AC_MAXNUMTRANSCONF = 6
    AC_MONITORDIGITSUPPORT = 7
    AC_GENERATEDIGITSUPPORT = 8
    AC_GENERATETONEMODES = 9
    AC_GENERATETONEMAXNUMFREQ = 10
    AC_MONITORTONEMAXNUMFREQ = 11
    AC_MONITORTONEMAXNUMENTRIES = 12
    AC_DEVCAPFLAGS = 13
    AC_ANSWERMODES = 14
    AC_LINEFEATURES = 15
    AC_SETTABLEDEVSTATUS = 16
    AC_PARKSUPPORT = 17
    AC_CALLERIDSUPPORT = 18
    AC_CALLEDIDSUPPORT = 19
    AC_CONNECTEDIDSUPPORT = 20
    AC_REDIRECTIONIDSUPPORT = 21
    AC_REDIRECTINGIDSUPPORT = 22
    AC_ADDRESSCAPFLAGS = 23
    AC_CALLFEATURES1 = 24
    AC_CALLFEATURES2 = 25
    AC_REMOVEFROMCONFCAPS = 26
    AC_REMOVEFROMCONFSTATE = 27
    AC_TRANSFERMODES = 28
    AC_ADDRESSFEATURES = 29
    AC_PREDICTIVEAUTOTRANSFERSTATES = 30
    AC_MAXCALLDATASIZE = 31
    AC_LINEID = 32
    AC_ADDRESSID = 33
    AC_FORWARDMODES = 34
    AC_MAXFORWARDENTRIES = 35
    AC_MAXSPECIFICENTRIES = 36
    AC_MINFWDNUMRINGS = 37
    AC_MAXFWDNUMRINGS = 38
    AC_MAXCALLCOMPLETIONS = 39
    AC_CALLCOMPLETIONCONDITIONS = 40
    AC_CALLCOMPLETIONMODES = 41
    AC_PERMANENTDEVICEID = 42
    AC_GATHERDIGITSMINTIMEOUT = 43
    AC_GATHERDIGITSMAXTIMEOUT = 44
    AC_GENERATEDIGITMINDURATION = 45
    AC_GENERATEDIGITMAXDURATION = 46
    AC_GENERATEDIGITDEFAULTDURATION = 47


class ADDRESS_CAPABILITY_STRING(Enum):
    ACS_PROTOCOL = 0
    ACS_ADDRESSDEVICESPECIFIC = 1
    ACS_LINEDEVICESPECIFIC = 2
    ACS_PROVIDERSPECIFIC = 3
    ACS_SWITCHSPECIFIC = 4
    ACS_PERMANENTDEVICEGUID = 5


class QOS_EVENT(Enum):
    QE_NOQOS = 1
    QE_ADMISSIONFAILURE = 2
    QE_POLICYFAILURE = 3
    QE_GENERICERROR = 4
    QE_LASTITEM = 4


class ADDRESS_EVENT(Enum):
    AE_STATE = 0
    AE_CAPSCHANGE = 1
    AE_RINGING = 2
    AE_CONFIGCHANGE = 3
    AE_FORWARD = 4
    AE_NEWTERMINAL = 5
    AE_REMOVETERMINAL = 6
    AE_MSGWAITON = 7
    AE_MSGWAITOFF = 8
    AE_LASTITEM = 8


class TERMINAL_STATE(Enum):
    TS_INUSE = 0
    TS_NOTINUSE = 1


class TERMINAL_TYPE(Enum):
    TT_STATIC = 0
    TT_DYNAMIC = 1


class TERMINAL_DIRECTION(Enum):
    TD_CAPTURE = 0
    TD_RENDER = 1
    TD_BIDIRECTIONAL = 2
    TD_MULTITRACK_MIXED = 3
    TD_NONE = 4


class CALL_MEDIA_EVENT(Enum):
    CME_NEW_STREAM = 0
    CME_STREAM_FAIL = 1
    CME_TERMINAL_FAIL = 2
    CME_STREAM_NOT_USED = 3
    CME_STREAM_ACTIVE = 4
    CME_STREAM_INACTIVE = 5
    CME_LASTITEM = 5


class CALL_MEDIA_EVENT_CAUSE(Enum):
    CMC_UNKNOWN = 0
    CMC_BAD_DEVICE = 1
    CMC_CONNECT_FAIL = 2
    CMC_LOCAL_REQUEST = 3
    CMC_REMOTE_REQUEST = 4
    CMC_MEDIA_TIMEOUT = 5
    CMC_MEDIA_RECOVERED = 6
    CMC_QUALITY_OF_SERVICE = 7


class TAPIOBJECT_EVENT(Enum):
    TE_ADDRESSCREATE = 0
    TE_ADDRESSREMOVE = 1
    TE_REINIT = 2
    TE_TRANSLATECHANGE = 3
    TE_ADDRESSCLOSE = 4
    TE_PHONECREATE = 5
    TE_PHONEREMOVE = 6


class PHONE_PRIVILEGE(Enum):
    PP_OWNER = 0
    PP_MONITOR = 1


class PHONECAPS_LONG(Enum):
    PCL_HOOKSWITCHES = 0
    PCL_HANDSETHOOKSWITCHMODES = 1
    PCL_HEADSETHOOKSWITCHMODES = 2
    PCL_SPEAKERPHONEHOOKSWITCHMODES = 3
    PCL_DISPLAYNUMROWS = 4
    PCL_DISPLAYNUMCOLUMNS = 5
    PCL_NUMRINGMODES = 6
    PCL_NUMBUTTONLAMPS = 7
    PCL_GENERICPHONE = 8


class PHONECAPS_STRING(Enum):
    PCS_PHONENAME = 0
    PCS_PHONEINFO = 1
    PCS_PROVIDERINFO = 2


class PHONE_BUTTON_MODE(Enum):
    PBM_DUMMY = 0
    PBM_CALL = 1
    PBM_FEATURE = 2
    PBM_KEYPAD = 3
    PBM_LOCAL = 4
    PBM_DISPLAY = 5


class PHONE_BUTTON_FUNCTION(Enum):
    PBF_UNKNOWN = 0
    PBF_CONFERENCE = 1
    PBF_TRANSFER = 2
    PBF_DROP = 3
    PBF_HOLD = 4
    PBF_RECALL = 5
    PBF_DISCONNECT = 6
    PBF_CONNECT = 7
    PBF_MSGWAITON = 8
    PBF_MSGWAITOFF = 9
    PBF_SELECTRING = 10
    PBF_ABBREVDIAL = 11
    PBF_FORWARD = 12
    PBF_PICKUP = 13
    PBF_RINGAGAIN = 14
    PBF_PARK = 15
    PBF_REJECT = 16
    PBF_REDIRECT = 17
    PBF_MUTE = 18
    PBF_VOLUMEUP = 19
    PBF_VOLUMEDOWN = 20
    PBF_SPEAKERON = 21
    PBF_SPEAKEROFF = 22
    PBF_FLASH = 23
    PBF_DATAON = 24
    PBF_DATAOFF = 25
    PBF_DONOTDISTURB = 26
    PBF_INTERCOM = 27
    PBF_BRIDGEDAPP = 28
    PBF_BUSY = 29
    PBF_CALLAPP = 30
    PBF_DATETIME = 31
    PBF_DIRECTORY = 32
    PBF_COVER = 33
    PBF_CALLID = 34
    PBF_LASTNUM = 35
    PBF_NIGHTSRV = 36
    PBF_SENDCALLS = 37
    PBF_MSGINDICATOR = 38
    PBF_REPDIAL = 39
    PBF_SETREPDIAL = 40
    PBF_SYSTEMSPEED = 41
    PBF_STATIONSPEED = 42
    PBF_CAMPON = 43
    PBF_SAVEREPEAT = 44
    PBF_QUEUECALL = 45
    PBF_NONE = 46
    PBF_SEND = 47


class PHONE_BUTTON_STATE(Enum):
    PBS_UP = 1
    PBS_DOWN = 2
    PBS_UNKNOWN = 4
    PBS_UNAVAIL = 8


class PHONE_HOOK_SWITCH_DEVICE(Enum):
    PHSD_HANDSET = 1
    PHSD_SPEAKERPHONE = 2
    PHSD_HEADSET = 4


class PHONE_HOOK_SWITCH_STATE(Enum):
    PHSS_ONHOOK = 1
    PHSS_OFFHOOK_MIC_ONLY = 2
    PHSS_OFFHOOK_SPEAKER_ONLY = 4
    PHSS_OFFHOOK = 8


class PHONECAPS_BUFFER(Enum):
    PCB_DEVSPECIFICBUFFER = 0


class PHONE_LAMP_MODE(Enum):
    LM_DUMMY = 1
    LM_OFF = 2
    LM_STEADY = 4
    LM_WINK = 8
    LM_FLASH = 1
    LM_FLUTTER = 2
    LM_BROKENFLUTTER = 4
    LM_UNKNOWN = 8


class AGENT_SESSION_STATE(Enum):
    ASST_NOT_READY = 0
    ASST_READY = 1
    ASST_BUSY_ON_CALL = 2
    ASST_BUSY_WRAPUP = 3
    ASST_SESSION_ENDED = 4


class AGENT_STATE(Enum):
    AS_NOT_READY = 0
    AS_READY = 1
    AS_BUSY_ACD = 2
    AS_BUSY_INCOMING = 3
    AS_BUSY_OUTGOING = 4
    AS_UNKNOWN = 5


class AGENT_EVENT(Enum):
    AE_NOT_READY = 0
    AE_READY = 1
    AE_BUSY_ACD = 2
    AE_BUSY_INCOMING = 3
    AE_BUSY_OUTGOING = 4
    AE_UNKNOWN = 5


class AGENT_SESSION_EVENT(Enum):
    ASE_NEW_SESSION = 0
    ASE_NOT_READY = 1
    ASE_READY = 2
    ASE_BUSY = 3
    ASE_WRAPUP = 4
    ASE_END = 5


class ACDGROUP_EVENT(Enum):
    ACDGE_NEW_GROUP = 0
    ACDGE_GROUP_REMOVED = 1


class ACDQUEUE_EVENT(Enum):
    ACDQE_NEW_QUEUE = 0
    ACDQE_QUEUE_REMOVED = 1


class AGENTHANDLER_EVENT(Enum):
    AHE_NEW_AGENTHANDLER = 0
    AHE_AGENTHANDLER_REMOVED = 1


class CALLINFOCHANGE_CAUSE(Enum):
    CIC_OTHER = 0
    CIC_DEVSPECIFIC = 1
    CIC_BEARERMODE = 2
    CIC_RATE = 3
    CIC_APPSPECIFIC = 4
    CIC_CALLID = 5
    CIC_RELATEDCALLID = 6
    CIC_ORIGIN = 7
    CIC_REASON = 8
    CIC_COMPLETIONID = 9
    CIC_NUMOWNERINCR = 10
    CIC_NUMOWNERDECR = 11
    CIC_NUMMONITORS = 12
    CIC_TRUNK = 13
    CIC_CALLERID = 14
    CIC_CALLEDID = 15
    CIC_CONNECTEDID = 16
    CIC_REDIRECTIONID = 17
    CIC_REDIRECTINGID = 18
    CIC_USERUSERINFO = 19
    CIC_HIGHLEVELCOMP = 20
    CIC_LOWLEVELCOMP = 21
    CIC_CHARGINGINFO = 22
    CIC_TREATMENT = 23
    CIC_CALLDATA = 24
    CIC_PRIVILEGE = 25
    CIC_MEDIATYPE = 26
    CIC_LASTITEM = 27


class TAPI_TONEMODE(Enum):
    TTM_RINGBACK = 2
    TTM_BUSY = 4
    TTM_BEEP = 8
    TTM_BILLING = 16


class TAPI_GATHERTERM(Enum):
    TGT_BUFFERFULL = 1
    TGT_TERMDIGIT = 2
    TGT_FIRSTTIMEOUT = 4
    TGT_INTERTIMEOUT = 8
    TGT_CANCEL = 16


class PHONE_TONE(Enum):
    PT_KEYPADZERO = 0
    PT_KEYPADONE = 1
    PT_KEYPADTWO = 2
    PT_KEYPADTHREE = 3
    PT_KEYPADFOUR = 4
    PT_KEYPADFIVE = 5
    PT_KEYPADSIX = 6
    PT_KEYPADSEVEN = 7
    PT_KEYPADEIGHT = 8
    PT_KEYPADNINE = 9
    PT_KEYPADSTAR = 10
    PT_KEYPADPOUND = 11
    PT_KEYPADA = 12
    PT_KEYPADB = 13
    PT_KEYPADC = 14
    PT_KEYPADD = 15
    PT_NORMALDIALTONE = 16
    PT_EXTERNALDIALTONE = 17
    PT_BUSY = 18
    PT_RINGBACK = 19
    PT_ERRORTONE = 20
    PT_SILENCE = 21


class TERMINAL_MEDIA_STATE(Enum):
    TMS_IDLE = 0
    TMS_ACTIVE = 1
    TMS_PAUSED = 2
    TMS_LASTITEM = 2


class FT_STATE_EVENT_CAUSE(Enum):
    FTEC_NORMAL = 0
    FTEC_END_OF_FILE = 1
    FTEC_READ_ERROR = 2
    FTEC_WRITE_ERROR = 3


class PHONE_EVENT(Enum):
    PE_DISPLAY = 0
    PE_LAMPMODE = 1
    PE_RINGMODE = 2
    PE_RINGVOLUME = 3
    PE_HOOKSWITCH = 4
    PE_CAPSCHANGE = 5
    PE_BUTTON = 6
    PE_CLOSE = 7
    PE_NUMBERGATHERED = 8
    PE_DIALING = 9
    PE_ANSWER = 10
    PE_DISCONNECT = 11
    PE_LASTITEM = 12


class FULLDUPLEX_SUPPORT(Enum):
    FDS_SUPPORTED = 0
    FDS_NOTSUPPORTED = 1
    FDS_UNKNOWN = 2
